stages:
  - stage: Terraform Apply
    displayName: Terraform Apply and Destroy
    jobs:
      - job: Terraform_Apply
        displayName: Terraform Apply
        steps:
          - task: ExtractFiles@1
            displayName: "Extract files "
            inputs:
              archiveFilePatterns: $(System.ArtifactsDirectory)/_TerraformPlan$(Build.BuildId)-tfplan/$(Build.BuildId)-tfplan.tgz
              destinationFolder: $(System.DefaultWorkingDirectory)/
              cleanDestinationFolder: false
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: Install Terraform 1.3.7
            inputs:
              terraformVersion: 1.3.7
          - task: CmdLine@2
            displayName: Terraform Init
            inputs:
              script: terraform init -backend-config="access_key=$(stdevtfstate12-key1)"
              workingDirectory: $(System.DefaultWorkingDirectory)/
          - task: CmdLine@2
            displayName: Terraform Apply
            inputs:
              script: terraform apply -auto-approve -input=false tfplan
              workingDirectory: $(System.DefaultWorkingDirectory)/
  - stage: Terraform Destroy
    displayName: Terraform Apply and Destroy
    jobs:
      - job: Terraform_Apply
        displayName: Terraform Apply
        steps:
          - task: ExtractFiles@1
            displayName: "Extract files "
            inputs:
              archiveFilePatterns: $(System.ArtifactsDirectory)/_TerraformPlan$(Build.BuildId)-tfplan/$(Build.BuildId)-tfplan.tgz
              destinationFolder: $(System.DefaultWorkingDirectory)/
              cleanDestinationFolder: false
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: Install Terraform 1.3.7
            inputs:
              terraformVersion: 1.3.7
          - task: CmdLine@2
            displayName: Terraform Init
            inputs:
              script: terraform init -backend-config="access_key=$(stdevtfstate12-key1)"
              workingDirectory: $(System.DefaultWorkingDirectory)/
          - task: CmdLine@2
            displayName: Terraform Destroy
            inputs:
              script: terraform destroy -auto-approve
              workingDirectory: $(System.DefaultWorkingDirectory)/
